ACE_MQ_TLS_MA_BOOTSTRAP_LDIF_PATH=${DEPLOYMENT_ROOT}/ldap/bootstrap.ldif

ACE_MQ_TLS_MA_MQ_SERVER_KEY_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-mq-server.key
ACE_MQ_TLS_MA_MQ_SERVER_CERT_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-mq-server.crt
ACE_MQ_TLS_MA_CA_CERT_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ca.crt
ACE_MQ_TLS_MA_CONFIG_MQSC_PATH=${DEPLOYMENT_ROOT}/mq/config.mqsc

CLIENT_JKS_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-client.jks
CA_JKS_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ca.jks

CA_CERT_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ca.crt


ACE_MQ_TLS_MA_CCDT_JSON_PATH=${DEPLOYMENT_ROOT}/mq/ccdt.json
ACE_MQ_TLS_MA_MQ_CLIENT_KDB_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ace-server.kdb
ACE_MQ_TLS_MA_MQ_CLIENT_STH_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ace-server.sth

ACE_MQ_TLS_MA_ACE_SERVER_KDB_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ace-server.kdb
ACE_MQ_TLS_MA_ACE_SERVER_STH_PATH=${DEPLOYMENT_ROOT}/certs/${PREFIX}-ace-server.sth
ACE_MQ_TLS_MA_POLICY_PROJECT_PATH=${DEPLOYMENT_ROOT}/ace/initial-config/policy/mq.policyxml
ACE_MQ_TLS_MA_SERVERCONF_PATH=${DEPLOYMENT_ROOT}/ace/initial-config/serverconf/server.conf.yaml
ACE_MQ_TLS_MA_SETDBPARMS_PATH=${DEPLOYMENT_ROOT}/ace/initial-config/setdbparms/setdbparms.txt